main: logan.pickpocket.main.PickpocketPlugin
name: PickPocket
version: 2.4
author: escape9179
api-version: "1.13"
softdepend: [ Vault, WorldGuard, WorldEdit ]
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
