main: logan.pickpocket.main.PickpocketPlugin
name: PickPocket
version: 3.0
author: escape9179
api-version: "1.13"
softdepend: [ Vault ]
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
